- name: installing nginx
  hosts: all
  become: ubuntu
  vars:
    ansible_python_interpreter: /home/ubuntu/myenv/bin/python
- name: update cache
  apt:
    update_cache: yes

- name: install nginix
  apt:
  name: nginx
  state: present

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

