# playbook to call the files | mster play book
- name: maste files
  become: yes
  become_user: ubuntu
  hosts: webservers
  ignore_errors: true
  roles:
  - nginix

#- hosts: db
#  roles:
#  - dbservers

